library(forecast)
library(ggplot2)
library(tseries)
library(urca)
library(zoo)
set.seed(120)
mydata=runif(n=100, min=10, max=45)
mytimeseries=ts(data=mydata, start=1955, frequency=4)
plot(mytimeseries)
class(mytimeseries)



plot(decompose(mytimeseries))
plot(forecast(auto.arima(mytimeseries)), h=5)

autoplot(mytimeseries)
autoplot(mytimeseries)+ggtitle("Autoplot of Stock Prices of Company A")
ggseasonplot(mytimeseries)
ggmonthplot(mytimeseries)
seasonplot(mytimeseries, xlab="", col=c("red", "blue"), year.labels=T, labelgap=0.35, type="l", bty="l", cex=0.5, main="Stock Prices of Company A")
seasonplot(mytimeseries, xlab="", col=c("red", "blue"), year.labels=T, labelgap=0.35, type="s", bty="l", cex=0.5, main="Stock Prices of Company A")
seasonplot(mytimeseries, xlab="", col=c("red", "blue"), year.labels=T, labelgap=0.35, type="p", bty="l", cex=0.5, main="Stock Prices of Company A")

meanm <- meanf (mytimeseries, h=20)
naivem <- naive(mytimeseries, h=20)
driftm <- rwf(mytimeseries, h=20, drift=T)
plot(meanm, plot.conf = F, main ="")
lines(naivem$mean, col=123, lwd =0.5)
lines(driftm$mean, col=22, lwd=2)
legend("topleft", lty=1, col=c(4, 123, 22), legend= c("Mean method", "Naive method", "Drift method"))
mytstrain<- window(mytimeseries, start= 1955, end= 1974)
plot(mytstrain)
library(forecast)
meanm<-meanf(mytstrain, h=20)
naivem<-naive(mytstrain, h=20)
driftm<-rwf(mytstrain, h=20, drift=T)
mytstest <- window (mytimeseries, start = 1975, end=1980)
accuracy(meanm, mytstest)
accuracy(naivem, mytstest)
accuracy(driftm, mytstest)
var(meanm$residuals)
mean(meanm$residuals)
mean(naivem$residuals)
naivwithoutNA<- naivem$residuals
naivwithoutNA<- naivwithoutNA[2:200]
var(naivwithoutNA)
mean(naivwithoutNA)
driftwithoutNA<-driftm$residuals
driftwithoutNA<-driftwithoutNA[2:200]
var(driftwithoutNA)
mean(driftwithoutNA)
hist(driftm$residuals)
adf.test(mytimeseries)
y<-diffinv(mytimeseries)
plot(y)
adf.test(y)
library(lmtest)
dwtest(lynx[-100]~lynx[-1])
acf(mytimeseries, lag.max=20)
pacf(mytimeseries, lag.max=20, plot=F)
shapiro.test(naivem$residuals)
plot(naivem$residuals)
mean(naivem$residuals[2:200])
hist(naivem$residuals)
acf(naivem$residuals[2:200])
plot(mytimeseries)
frequency(mytimeseries)
length(mytimeseries)
decompose(mytimeseries, type="additive")
plot(decompose(mytimeseries, type="additive"))
autoplot(decompose(mytimeseries, type="additive"))
plot(stl(mytimeseries, s.window="periodic"))   
mytimeseries1=(decompose(mytimeseries, "additive"))     
class(mytimeseries1)
mytimeseriesadjusted = mytimeseries - mytimeseries1$seasonal
plot(mytimeseriesadjusted)
library(forecast)
plot(stlf(mytimeseries, method= "arima"))
plot(mytimeseries1$seasonal)
mymodel1= decompose(mytimeseries, type = "additive")
mymodel2=decompose(mytimeseries, type = "multiplicative")
plot(mymodel1)
plot(mymodel2)
plot(mymodel1$trend + mymodel1$random)
library(TTR)
x=c(1,2,3,4,5,6,7)
SMA(x, n=3)
mytimeseriessmoothed= SMA(mytimeseries, n=4)
plot(mytimeseries)
plot(mytimeseriessmoothed)
library(forecast)
etsmodel = ets(mytimeseries)
plot(mytimeseries, lwd =3)
lines(etsmodel$fitted, col= "red")
plot(forecast(etsmodel, h=12))
plot(forecast(etsmodel, h =12, level =95))
etsmodmult= ets(mytimeseries, model = "MZM")
plot(mytimeseries, lwd =3)
lines(etsmodmult$fitted, col= "red")
tsdisplay(mytimeseries)
auto.arima(mytimeseries)
auto.arima(mytimeseries, trace=T)
auto.arima(mytimeseries, trace=T, stepwise=F, approximation=F)
myarima=arima(mytimeseries, order= c(2,0,0))
myarima
tail(mytimeseries)
residuals(myarima)
myarima1=arima(mytimeseries, order= c(0,0,2))
myarima1
tail(mytimeseries)
residuals(myarima1)
